export const BackgroundColor = [
  { name: "red", color: "to-red-500/40" },
  { name: "pink", color: "to-pink-500/30" },
  { name: "green", color: "to-green-500/30" },
  { name: "blue", color: "to-sky-500/50" },
  { name: "purple", color: "to-purple-500/40" },
  { name: "yellow", color: "to-yellow-500/40" },
  { name: "brown", color: "to-yellow-950/50" },
  { name: "white", color: "to-white/30" },
  { name: "gray", color: "to-gray-500/80" },
  { name: "black", color: "to-black/80" },
];

export const TypesColorSAVE = [
  {
    name: "normal",
    colorBg: "bg-neutral-600",
    colorText: "text-neutral-300",
    colorBorder: "border-neutral-300",
  },
  {
    name: "dragon",
    colorBg: "bg-gray-800",
    colorText: "text-gray-300",
    colorBorder: "border-gray-300",
  },
  {
    name: "steel",
    colorBg: "bg-zinc-500",
    colorText: "text-zinc-300",
    colorBorder: "border-zinc-300",
  },
  {
    name: "rock",
    colorBg: "bg-stone-700",
    colorText: "text-stone-400",
    colorBorder: "border-stone-400",
  },
  {
    name: "poison",
    colorBg: "bg-purple-500",
    colorText: "text-purple-500",
    colorBorder: "border-purple-500",
  },
  {
    name: "psychic",
    colorBg: "bg-purple-500",
    colorText: "text-purple-500",
    colorBorder: "border-purple-500",
  },
  {
    name: "ghost",
    colorBg: "bg-purple-900",
    colorText: "text-purple-500",
    colorBorder: "border-purple-500",
  },
  {
    name: "grass",
    colorBg: "bg-green-600",
    colorText: "text-green-500",
    colorBorder: "border-green-500",
  },
  {
    name: "bug",
    colorBg: "bg-red-500",
    colorText: "text-red-500",
    colorBorder: "border-red-500",
  },
  {
    name: "fighting",
    colorBg: "bg-red-700",
    colorText: "text-red-600",
    colorBorder: "border-red-600",
  },
  {
    name: "fire",
    colorBg: "bg-orange-500",
    colorText: "text-orange-500",
    colorBorder: "border-orange-500",
  },
  {
    name: "fairy",
    colorBg: "bg-pink-500",
    colorText: "text-pink-500",
    colorBorder: "border-pink-500",
  },
  {
    name: "flying",
    colorBg: "bg-sky-400",
    colorText: "text-sky-400",
    colorBorder: "border-sky-400",
  },
  {
    name: "ice",
    colorBg: "bg-cyan-500",
    colorText: "text-cyan-500",
    colorBorder: "border-cyan-500",
  },
  {
    name: "water",
    colorBg: "bg-blue-600",
    colorText: "text-blue-500",
    colorBorder: "border-blue-500",
  },
  {
    name: "electric",
    colorBg: "bg-yellow-500",
    colorText: "text-yellow-400",
    colorBorder: "border-yellow-400",
  },
  {
    name: "ground",
    colorBg: "bg-yellow-900",
    colorText: "text-amber-500",
    colorBorder: "border-amber-500",
  },
  {
    name: "dark",
    colorBg: "bg-black/80",
    colorText: "text-black",
    colorBorder: "border-gray-300",
  },
];

export const TypesColor = [
  {
    name: "normal",
    colorBg: "bg-neutral-200",
    colorText: "text-neutral-500",
    colorBorder: "border-neutral-300",
  },
  {
    name: "dragon",
    colorBg: "bg-gray-200",
    colorText: "text-gray-600",
    colorBorder: "border-gray-300",
  },
  {
    name: "steel",
    colorBg: "bg-zinc-200",
    colorText: "text-zinc-500",
    colorBorder: "border-zinc-300",
  },
  {
    name: "rock",
    colorBg: "bg-stone-200",
    colorText: "text-stone-500",
    colorBorder: "border-stone-400",
  },
  {
    name: "poison",
    colorBg: "bg-purple-200",
    colorText: "text-purple-600",
    colorBorder: "border-purple-500",
  },
  {
    name: "psychic",
    colorBg: "bg-purple-200",
    colorText: "text-purple-500",
    colorBorder: "border-purple-500",
  },
  {
    name: "ghost",
    colorBg: "bg-purple-900",
    colorText: "text-gray-200",
    colorBorder: "border-purple-500",
  },
  {
    name: "grass",
    colorBg: "bg-green-200",
    colorText: "text-green-500",
    colorBorder: "border-green-500",
  },
  {
    name: "bug",
    colorBg: "bg-red-200",
    colorText: "text-red-500",
    colorBorder: "border-red-500",
  },
  {
    name: "fighting",
    colorBg: "bg-red-300",
    colorText: "text-red-600",
    colorBorder: "border-red-600",
  },
  {
    name: "fire",
    colorBg: "bg-orange-200",
    colorText: "text-orange-500",
    colorBorder: "border-orange-500",
  },
  {
    name: "fairy",
    colorBg: "bg-pink-200",
    colorText: "text-pink-500",
    colorBorder: "border-pink-500",
  },
  {
    name: "flying",
    colorBg: "bg-sky-200",
    colorText: "text-sky-500",
    colorBorder: "border-sky-400",
  },
  {
    name: "ice",
    colorBg: "bg-cyan-200",
    colorText: "text-cyan-500",
    colorBorder: "border-cyan-500",
  },
  {
    name: "water",
    colorBg: "bg-blue-200",
    colorText: "text-blue-500",
    colorBorder: "border-blue-500",
  },
  {
    name: "electric",
    colorBg: "bg-yellow-200",
    colorText: "text-yellow-500",
    colorBorder: "border-yellow-400",
  },
  {
    name: "ground",
    colorBg: "bg-gray-200",
    colorText: "text-amber-700",
    colorBorder: "border-amber-500",
  },
  {
    name: "dark",
    colorBg: "bg-white/60",
    colorText: "text-black",
    colorBorder: "border-gray-300",
  },
];

//export default {BackgroundColor, TypesColor};
